CambioTotalFrontEnd/CambioTotalFrontEnd/Controllers/InicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CambioTotalED;
using CambioTotalFrontEnd.Filters;
using CambioTotalTD;
using FrontendUtil;

namespace CambioTotalFrontEnd.Controllers
{
    public class InicioController : Controller
    {
        tdUsuario itdusuario;
        tdOperacion itOperacion;

        public ActionResult Index()
        {
            ViewBag.DirIP = UtlAuditoria.ObtenerDireccionIP();
            return View();
        }

        public ActionResult inicio(int? ivalorsesion, string valorlogin)
        {
            if (ivalorsesion != 1 || ivalorsesion == null)
            {
                ivalorsesion = 0;
            }

            ViewBag.GIvalorError = valorlogin;
            ViewBag.GIvalorSesion = ivalorsesion;
            return View();
        }

        public ActionResult registro()
        {

            return View();
        }

        [ValidadorSesion]
        public ActionResult principal()
        {
            ViewBag.MenuPrincipal = "active";
            int irolusuario = UtlAuditoria.ObtenerTipoUsuario();
            string susuario = UtlAuditoria.ObtenerNombre() + " " + UtlAuditoria.ObtenerApellido();
            int gidusuario = UtlAuditoria.ObtenerIdUsuario();
            ViewBag.GrolUsuario = irolusuario;
            ViewBag.GNombreUsuario = susuario;
            ViewBag.GgradoUsuario = 0;
            ViewBag.GIdusuario = gidusuario;
            ViewBag.GImagenUsuario = UtlAuditoria.ObtenerImagenUsuario();
            return View();
        }

        [ValidadorSesion]
        public ActionResult miscuentas()
        {
            ViewBag.MenuPrincipal = "active";
            int irolusuario = UtlAuditoria.ObtenerTipoUsuario();
            int gidusuario = UtlAuditoria.ObtenerIdUsuario();
            string susuario = UtlAuditoria.ObtenerNombre() + " " + UtlAuditoria.ObtenerApellido();

            ViewBag.GrolUsuario = irolusuario;
            ViewBag.GNombreUsuario = susuario;
            ViewBag.GgradoUsuario = 0;
            ViewBag.GIdusuario = gidusuario;
            ViewBag.GImagenUsuario = UtlAuditoria.ObtenerImagenUsuario();
            return View();
        }


        [ValidadorSesion]
        public ActionResult GestionTransacciones()
        {
            ViewBag.MenuPrincipal = "active";
            int irolusuario = UtlAuditoria.ObtenerTipoUsuario();
            string susuario = UtlAuditoria.ObtenerNombre() + " " + UtlAuditoria.ObtenerApellido();
            int gidusuario = UtlAuditoria.ObtenerIdUsuario();
            ViewBag.GrolUsuario = irolusuario;
            ViewBag.GNombreUsuario = susuario;
            ViewBag.GgradoUsuario = 0;
            ViewBag.GIdusuario = gidusuario;
            ViewBag.GImagenUsuario = UtlAuditoria.ObtenerImagenUsuario();
            return View();
        }

        /* LLAMADOS */
        [HttpPost]
        public JsonResult IniciarSesion(string wusuario, string wclave)
        {
            try
            {
                var objResultado = new object();
                edUsuario oedusuario = new edUsuario();
                itdusuario = new tdUsuario();
                oedusuario = itdusuario.tdObtenerUsuario(wusuario, wclave);

                if (oedusuario.scorreo == "0" || oedusuario.snombres == "0" || oedusuario.snombres == "0")
                {
                    objResultado = new
                    {
                        iResultado = -3,
                        iResultadoIns = "Usuario o clave incorrectos"
                    };
                    return Json(objResultado);
                }
                Dictionary<string, string> DVariables = new Dictionary<string, string>();
                DVariables["IDUSUARIO"] = oedusuario.idusuario.ToString();
                DVariables["SNOMBRE"] = oedusuario.snombres.ToString();
                DVariables["APELLIDO"] = oedusuario.sapellidos.ToString();
                DVariables["SEMAIL"] = oedusuario.scorreo.ToString();
                DVariables["ITIPODOC"] = oedusuario.itipodocumento.ToString();
                DVariables["SDOCUMENTO"] = oedusuario.sdocumento.ToString();
                DVariables["TIPOUSUARIO"] = oedusuario.itipousuario.ToString();
                DVariables["CELULAR"] = oedusuario.scelular.ToString();
                //DVariables["IMAGENUSUARIO"] = oedusuario.simagen.ToString();
                DVariables["SRUC"] = oedusuario.sruc.ToString();
                DVariables["SRAZONSOCIAL"] = oedusuario.srazonsocial.ToString();
                UtlAuditoria.SetSessionValues(DVariables);

                objResultado = new
                {
                    iResultado = oedusuario.itipousuario,
                    iResultadoIns = "Inicio/Principal"
                };
                return Json(objResultado);
            }
            catch (Exception ex)
            {
                //UtlLog.toWrite(UtlConstantes.PizarraWEB, UtlConstantes.LogNamespace_PizarraWEB, this.GetType().Name.ToString(), MethodBase.GetCurrentMethod().Name, UtlConstantes.LogTipoError, "", ex.StackTrace.ToString(), ex.Message.ToString());
                return Json(ex);
            }

        }

        [HttpPost]
        public JsonResult CrearUsuario(string wnombres, string wapellidos, int wtipodocumento, string wdocumento, string wfechanacimiento,
            string wfecharegistro, string whoraregistro, int wtipousuario, string wcorreo, string wclave, string wtoken,
            string wruc, string wrazonsocial, string wpep1, string wpep2, string wpep3, string wpep4, string wcelular)
        {
            try
            {
                var objResultado = new object();
                int iresultado = 0;
                itdusuario = new tdUsuario();
                edUsuario oedusuario = new edUsuario();
                iresultado = itdusuario.tdInsertarUsuario(wnombres, wapellidos, wtipodocumento, wdocumento, wfechanacimiento, wfecharegistro,
                                                        whoraregistro, wtipousuario, wcorreo, wclave, wtoken, wruc, wrazonsocial
                                                        , wpep1, wpep2, wpep3, wpep4, wcelular);
                if (iresultado == 0 || iresultado == -1 || iresultado == -2)
                {
                    objResultado = new
                    {
                        iResultado = -3,
                        iResultadoIns = "Usuario o clave incorrecta"
                    };
                    return Json(objResultado);
                }
                oedusuario = itdusuario.tdFiltrarUsuario(iresultado);
                Dictionary<string, string> DVariables = new Dictionary<string, string>();
                DVariables["IDUSUARIO"] = oedusuario.idusuario.ToString();
                DVariables["SNOMBRE"] = oedusuario.snombres.ToString();
                DVariables["APELLIDO"] = oedusuario.sapellidos.ToString();
                DVariables["SEMAIL"] = oedusuario.scorreo.ToString();
                DVariables["ITIPODOC"] = oedusuario.itipodocumento.ToString();
                DVariables["SDOCUMENTO"] = oedusuario.sdocumento.ToString();
                DVariables["TIPOUSUARIO"] = oedusuario.itipousuario.ToString();
                DVariables["CELULAR"] = oedusuario.scelular.ToString();
                //DVariables["IMAGENUSUARIO"] = oedusuario.simagen.ToString();
                DVariables["SRUC"] = oedusuario.sruc.ToString();
                DVariables["SRAZONSOCIAL"] = oedusuario.srazonsocial.ToString();
                UtlAuditoria.SetSessionValues(DVariables);

                objResultado = new
                {
                    iResultado = 1,
                    iResultadoIns = "Inicio/Principal"
                };
                return Json(objResultado);
            }
            catch (Exception ex)
            {
                //UtlLog.toWrite(UtlConstantes.PizarraWEB, UtlConstantes.LogNamespace_PizarraWEB, this.GetType().Name.ToString(), MethodBase.GetCurrentMethod().Name, UtlConstantes.LogTipoError, "", ex.StackTrace.ToString(), ex.Message.ToString());
                return Json(ex);
            }

        }

        [HttpPost]
        public JsonResult cerrarSesion()
        {
            var objResultado = new object();
            try
            {
                bool bResultado = UtlAuditoria.CerrarSession();
                if (bResultado)
                {
                    objResultado = new
                    {
                        iResultado = 1
                    };
                }
                else
                {
                    objResultado = new
                    {
                        iResultado = 2
                    };
                }
            }
            catch (Exception ex)
            {
                //UtlLog.toWrite(UtlConstantes.PizarraWEB, UtlConstantes.LogNamespace_PizarraWEB, this.GetType().Name.ToString(), MethodBase.GetCurrentMethod().Name, UtlConstantes.LogTipoError, "", ex.StackTrace.ToString(), ex.Message.ToString());
                throw ex;
            }
            return Json(objResultado);
        }

        //registra las tarjetas de la persona
        [HttpPost]
        public JsonResult OperacionCuentaBancaria(int wtipoOperacion, int widCuentBanc, int widusuario, int witipocuenta, int wimoneda
                                        , int wibanco, string wbanco, string wnumerocuenta, string wnumerocuentainterbancaria, string wnombrecuenta, int witipodeclaracion
                                        , string wtitular, string wfecReg, string whoraReg)
        {
            try
            {
                var objResultado = new object();
                int iresultado = 0;
                itOperacion = new tdOperacion();

                iresultado = itOperacion.tdOperacionCuentaBancaria(wtipoOperacion, widCuentBanc, widusuario, witipocuenta, wimoneda

CambioTotalFrontEnd/CambioTotalFrontEnd/Views/Inicio/inicio.cshtml
@*@{
    ViewBag.Title = "inicio";
    Layout = "~/Views/Shared/_LayoutCuenta.cshtml";
}*@

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <title>Casa de cambio | Inicio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description" />
    <meta content="Crivant" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/assets/tucambio.png">

    <!-- App css -->
    <link href="~/assets/css/vendor/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/css/app.min.css" rel="stylesheet" type="text/css" id="light-style" />
    <link href="~/assets/css/app-dark.min.css" rel="stylesheet" type="text/css" id="dark-style" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/css-loader/3.3.3/css-loader.css" rel="stylesheet" />

    <script>
         var RutaPrincipal = "@Url.Content("~")";
    </script>
</head>

<body class="authentication-bg pb-0" data-layout-config='{"darkMode":false}'>
    <div id="divcarga" class="loader loader-default" data-text="Cargando... por favor espere" blink></div>
    <input type="hidden" id="data-ivalorsesion" value="@ViewBag.GIvalorSesion" />

    <div class="account-pages mt-2 mb-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="card">
                        <!-- Logo-->
                        <div class="card-header pt-4 pb-4 text-center bg-success">
                            <a href="index.html">
                                @*<span><img src="assets/images/logo.png" alt="" height="18"></span>*@
                            </a>
                        </div>

                        <div class="card-body p-4">
                            <div class="text-center w-75 m-auto">
                                <h4 class="text-dark-50 text-center mt-0 font-weight-bold">Inicia Sesión</h4>
                                <p class="text-muted mb-4">Coloca tus credenciales para poder continuar cambiando y ahorrando</p>
                            </div>

                            <form action="#" id="frm1">
                                <div class="form-group">
                                    <label for="emailaddress">Correo</label>
                                    <input class="form-control" type="email" id="txcorreo" placeholder="Ingresa tu correo">
                                </div>

                                <div class="form-group">
                                    <label for="password">Contraseña</label>
                                    <div class="input-group input-group-merge">
                                        <input type="password" id="password" class="form-control" placeholder="Ingresa tu clave">
                                        <div class="input-group-append" data-password="false">
                                            <div class="input-group-text">
                                                <span class="password-eye"></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                @*<div class="form-group">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" class="custom-control-input" id="checkbox-signup">
                                        <label class="custom-control-label" for="checkbox-signup">I accept <a href="#" class="text-muted">Terms and Conditions</a></label>
                                    </div>
                                </div>*@

                                <div class="form-group mb-0 text-center">
                                    <button class="btn btn-success" id="btniniciar"> Iniciar Sesión </button>
                                </div>

                            </form>
                        </div> <!-- end card-body -->
                    </div>
                    <!-- end card -->

                    <div class="row mt-3">
                        <div class="col-12 text-center">
                            <p class="text-success">Eres nuevo? <a href="@Url.Action("registro","Inicio")" class="text-success ml-1"><b>Regístrate</b></a></p>
                        </div> <!-- end col-->
                    </div>
                    <!-- end row -->

                </div> <!-- end col -->
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div>
    <!-- end page -->



    <script src="~/assets/js/vendor.min.js"></script>
    <script src="~/assets/js/app.min.js"></script>
    <input type="hidden" id="idvalorerror" value="@ViewBag.GIvalorError" />

</body>
</html>

<script>
    $('#frm1').submit(false);

    function NotificacionInfoDerecha(mensaje) {
        $.NotificationApp.send("Aviso!", mensaje, "top-right", "rgba(0,0,0,0.2)", "info")
    }

    function NotificacionAvisoIzquierda(mensaje) {
        $.NotificationApp.send("AVISO!", mensaje, "top-left", "rgba(0,0,0,0.2)", "warning")
    }

    function NotificacionAvisoIzquierdaAbajo(mensaje) {
        $.NotificationApp.send("AVISO!", mensaje, "bottom-left", "rgba(0,0,0,0.2)", "warning")
    }

    function NotificacionErrorIzquierda(mensaje) {
        $.NotificationApp.send("ERROR!", mensaje, "top-left", "rgba(0,0,0,0.2)", "error")
    }

    function NotificacionSuccessIzquierda(mensaje) {
        $.NotificationApp.send("DATOS CORRECTOS!", mensaje, "top-left", "rgba(0,0,0,0.2)", "success")
    }

    var Givalorsesion = $('#data-ivalorsesion').val();
    if (Givalorsesion == 1) {
        NotificacionAvisoIzquierdaAbajo("La sesión ha terminado, por favor ingrese nuevamente sus credenciales.")
    }

    $(document).on('keypress', function (e) {
        if (e.which == 13) {
            $('#divcarga').addClass("is-active");
            var ipUsuario = $('#txcorreo').val();
            var ipClave = $('#password').val();
            if (ipUsuario.trim() == "") {
                NotificacionAvisoIzquierda("INGRESAR SU USUARIO");
                $('#divcarga').removeClass("is-active");
                return;
            }
            if (ipClave.trim() == "") {
                NotificacionAvisoIzquierda("INGRESE SU CLAVE");
                $('#divcarga').removeClass("is-active");
                return;
            }

            $.ajax({
                type: "POST",
                url: RutaPrincipal + 'Inicio/IniciarSesion',
                data: {
                    "wusuario": ipUsuario,
                    "wclave": ipClave
                },
                async: false,
                success: function (msg) {
                    if (msg.iResultado === -3) {
                        $('#divcarga').removeClass("is-active");
                        NotificacionErrorIzquierda("USUARIO O CLAVE INCORRECTO");
                        return;
                    } else {
                        if (msg.iResultado == 3) {
                            window.location.href = RutaPrincipal + "Inicio/GestionTransacciones";
                        } else {
                            window.location.href = RutaPrincipal + "Inicio/principal";
                        }

                    }
                },
                error: function (msg) {

                    //location.reload();
                },
                complete: function (data) {
                    // si acabo de completar
                }
            });
        }
    });

    $("#btniniciar").click(function () {
        var ipUsuario = $('#txcorreo').val();
        var ipClave = $('#password').val();
        if (ipUsuario.trim() == "") {
            NotificacionAvisoIzquierda("INGRESAR SU USUARIO");
            $('#divcarga').removeClass("is-active");
            return;
        }
        if (ipClave.trim() == "") {
            NotificacionAvisoIzquierda("INGRESE SU CLAVE");
            $('#divcarga').removeClass("is-active");
            return;
        }
        $('#divcarga').addClass("is-active");
        $.ajax({
            type: "POST",
            url: RutaPrincipal + 'Inicio/IniciarSesion',
            data: {
                "wusuario": ipUsuario,
                "wclave": ipClave
            },
            async: false,
            success: function (msg) {
                if (msg.iResultado === -3) {
                    $('#divcarga').removeClass("is-active");
                    NotificacionErrorIzquierda("USUARIO O CLAVE INCORRECTO");
                    return;
                } else {
                    if (msg.iResultado == 3) {
                        window.location.href = RutaPrincipal + "Inicio/GestionTransacciones";
                    } else {
                        window.location.href = RutaPrincipal + "Inicio/principal";
                    }
                    
                }
            },
            error: function (msg) {

                //location.reload();
            },
            complete: function (data) {
                // si acabo de completar
            }
        });

    });


</script>

CambioTotalFrontEnd/CambioTotalFrontEnd/Views/Inicio/nosotros.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .banner .mein-menu .navbar #navbarNavDropdown ul.navbar-nav li.nav-item a.nav-link {
        font-family: 'aileron.regular';
        color: #fff;
        font-size: 15px;
        line-height: 1.556;
        font-weight: 600;
        padding-right: 0;
        padding-left: 0;
    }
</style>
<section class="banner" style="background: linear-gradient(rgb(8 8 8 / 50%), rgb(14 14 14 / 50%)), url(../../assets/img2.jpeg);
    background-size: cover;background-position: center; background-repeat: no-repeat;padding-bottom: 40px;position: relative;">
    <div class="laptop">
        @*<img src="~/assets/img/laptop-man.png" class="man-lap" alt="">*@
    </div>
    <!-- Main-menu Strat -->
    <div class="mein-menu">
        <nav class="navbar navbar-expand-lg navbar-light ">
            <div class="container">
                <a class="navbar-brand" style="display: inline-flex;" href="@Url.Action("Index","Inicio")">
                    <img src="~/assets/tucambio.png" height="45" class="logo" alt="logo">
                    <h4 style="color:white;margin-top: 4%;">TuCambioTotal</h4>
                    <!-- <img src="assets/img/logo.png" class="logo" alt="logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="@Url.Action("Index","Inicio")">Inicio</a>
                        </li>
                        @*<li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Index","Inicio")">Nosotros</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Inicio")">¿Cómo funciona?</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Inicio")">Preguntas frecuentes</a>
                        </li>
                        <li class="nav-item">
                            <button class="button button-1" style="background-color:#f5ae08;border: 0;color:#fff;" onclick="window.location.href = '/Inicio/registro';">Regístrate</button>
                        </li>
                        <li class="nav-item">
                            <button class="button button-1" onclick="window.location.href = '/Inicio/inicio';">Iniciar sesión</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

</section>

<br />
<div class="row text-center justify-content-center mt-5">
    <div class="col-md-8">
        <h3 class="subtitle" style="color:green;">NOSOTROS</h3>
        <br />
        <h4>
            Somos una casa de cambio digital, nuestro objetivo es ofrecerte una forma rápida y segura de cambiar divisas donde quiera que estés.
            <br />
            <br />
            Contamos con un equipo especializado en tecnología que trabaja para darte el mejor servicio, priorizando tu seguridad y confianza.
        </h4>
        <br />

    </div>
</div>

<div>
    @*<div id="WhatsappBtn" style="z-index: 999;"></div>*@
    <style>
        div.ccw_plugin, .inline {
            display: inline;
        }

        .chatbot {
            position: fixed;
            z-index: 99999999;
        }

        .ccw_plugin .animated {
            animation-duration: 1s;
            animation-fill-mode: both;
        }
    </style>

    <div class="ccw_plugin chatbot" style="bottom:20px; right:30px;">
        <div class="style4 animated no-animation ccw-no-hover-an">
            <a target="_blank" href="https://web.whatsapp.com/send?phone=51941645017&text=" class="nofocus">
                <div class="chip style-4 ccw-analytics p-1" id="style-4" data-ccw="style-4" style="border-radius:10px;background-color: #00a24f; color: #fff">
                    <img id="s4-icon" data-ccw="style-4" alt=""
                         data-src="https://mendozacercoselectricos.com/wp-content/plugins/click-to-chat-for-whatsapp/./new/inc/assets/img/whatsapp-logo-32x32.png"
                         class="ccw-analytics lazyloaded"
                         src="https://mendozacercoselectricos.com/wp-content/plugins/click-to-chat-for-whatsapp/./new/inc/assets/img/whatsapp-logo-32x32.png">
                    Esperamos tu mensaje!
                </div>
            </a>
        </div>
    </div>

</div>


<style>
    @@media (max-width: 767px) {
        .footer .footer-bottom .social-style {
            text-align: center !important;
        }
    }
</style>
<div class="footer">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-3 mt-4 text-center">
                <h3 style="color: #00a24f;font-size: 30px;" class="subtitle">EMPRESA</h3>
                <a href="@Url.Action("nosotros","Inicio")" style="color:#000;font-weight:700;">Acerca de nosotros</a>
                <br />
                <p style="font-weight:700;">
                    Registro SBS: 01989-2021
                    <br />
                    RUC: 20607581275
                </p>
            </div>
            <div class="col-md-3 text-center mb-2">
                <h3 class="subtitle" style="color: #00a24f;font-size: 30px;">LEGAL</h3>
                <a href="@Url.Action("terminosycondiciones","Inicio")" style="color:#000;font-weight:700;">Términos y condiciones</a>
                <a href="@Url.Action("politicadeprivacidad","Inicio")" style="color:#000;font-weight:700;">Política de privacidad</a>
            </div>
            <div class="col-md-3 text-center mb-2">
                <h3 class="subtitle" style="color: #00a24f;font-size: 30px;">AYUDA</h3>
                <a href="#divfaq" style="color:#000;font-weight:700;">Preguntas Frecuentes</a>
                <a target="_blank" href="https://web.whatsapp.com/send?phone=51941645017&text=Hola%20Deseo%20una%20tasa%20preferencial" style="color:#000;font-weight:700;">Tasa Preferencial</a>
            </div>
            <div class="col-md-3 text-center mb-2">
                <h3 class="subtitle" style="color: #00a24f;font-size: 30px;">EMPIEZA</h3>
                <a href="@Url.Action("registro","Inicio")" style="font-size:19px;color:#000;font-weight:600;font-family: 'aileron.regular';">Regístrate</a>
                |
                <a href="@Url.Action("inicio","Inicio")" style="font-size:19px;color:#000;font-weight:600;font-family: 'aileron.regular';">Iniciar sesión</a>
                <a href="#divcomousar" style="font-size:19px;color:#000;font-weight:600;">¿Cómo funciona?</a>
            </div>

            <div class="col-md-6 text-center mb-2">
                <h3 class="subtitle" style="color: #00a24f;font-size: 30px;">CONTACTO</h3>
                <p style="font-weight:700;">
                    941645017
                    <br />
                    <a style="font-size:19px;color:#000;font-weight:400;font-family: 'aileron.regular';" href="mailto:contacto@tucambiototal.com">contacto@tucambiototal.com</a>
                </p>
            </div>
            <div class="col-md-6 mt-4 mb-5 text-center mb-2">
                <h3 class="subtitle" style="color: #00a24f;font-size: 30px;">REDES</h3>
                <div class="footer-bottom">
                    <div class="social-style" style="text-align: center;">
                        <a href="https://www.facebook.com/Tu-Cambio-Total-103825761901896" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a href="https://www.instagram.com/tucambiototalpe/" target="_blank"><i class="fab fa-instagram"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-lg-12 text-center mb-2">
                <div class="footer-box">
                    <a class="navbar-brand mt-1" style="display: inline-flex;" href="@Url.Action("Index","Inicio")">
                        <img src="~/assets/tucambio.png" height="45" class="logo" alt="logo">
                        <h4 class="ml-1" style="color:#00a24f;margin-top: 4%;">TuCambioTotal</h4>
                    </a>

                </div>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-12">
                <div class="raka"></div>
            </div>
            <div class="col-md-6">
                <div class="footer-bottom">
                    <p class="text" style="font-weight: 600;">
                        &copy; Todos los derechos reservados <a href="#">TuCambiototal</a> | <a href="#" style="font-weight: 600;">2021 &nbsp;<a style="font-size:14px;" href="https://www.crivant.com" target="_blank">Hecho por Crivant</a></a>
                    </p>
                </div>
            </div>
            <div class="col-md-6">

            </div>
        </div>
    </div>
</div>